### ISSUE TITLE
Page détail des offres

### ISSUE THREAD

**Issue by reunono** [GSOinteractive/page-offres#1]
Il va falloir intégrer la page "détail" d'une offre.
Attention, celle-ci sera intégrée dans le "layout" des pages profils (un header/footer). 
On peut reprendre un max de choses de la page principale.

![detail-offre](https://cloud.githubusercontent.com/assets/2212831/13853391/bf68ea1c-ec66-11e5-8d98-83bf40bbd9ca.jpg)

**Comment by abe33** [comment]
Il y a moyen d'avoir tout les pavés du bas en texte que je puisse le copier/coller ?

**Comment by reunono** [comment]
Sud Ouest chez moi chaque jour + accès numérique à l'Edition Abonnés + de 28% de réduction, soit mon abonnement mensuel à 24,90 € par mois au lieu de 34,80 €, sur la base du prix facial de Sud Ouest et Sud Ouest Dimanche au 2 mai 2015. A l'issue des 12 mois de réduction à 28%, les prélèvements suivants seront calculés sur la base du prix facial de Sud Ouest et Sud Ouest dimanche au moment du prélèvement. Offre réservée à nos nouveaux abonnés particuliers et aux non abonnés depuis plus de 6 mois.

-----

Sud Ouest chez moi chaque jour + accès numérique à l'Edition Abonnés + de 28% de réduction, soit mon abonnement mensuel à 24,90 € par mois au lieu de 34,80 €, sur la base du prix facial de Sud Ouest et Sud Ouest Dimanche au 2 mai 2015. A l'issue des 12 mois de réduction à 28%, les prélèvements suivants seront calculés sur la base du prix facial de Sud Ouest et Sud Ouest dimanche au moment du prélèvement. Offre réservée à nos nouveaux abonnés particuliers et aux non abonnés depuis plus de 6 mois.

![galaxy-tab-4](https://cloud.githubusercontent.com/assets/2212831/13916486/480c9796-ef5b-11e5-8fae-e00bab44384c.png)

**Comment by abe33** [comment]
Visible ici: http://gsointeractive.github.io/page-offres/details.html
